moviehub/mhub/mhub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hubapp.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

moviehub/mhub/hubapp/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=20, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='Category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

from django.conf import settings
from django.db import models

class Movie(models.Model):
    name = models.CharField(max_length=250)
    rating = models.DecimalField(max_digits=3, decimal_places=2)
    image = models.ImageField(upload_to='movies')
    description = models.TextField()
    release_year = models.IntegerField()
    actors = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    youtube_trailer_link = models.URLField()
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    # Add any other fields you want

    def __str__(self):
        return f"{self.user.username}'s Profile"

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)  # Assuming you're using Django's auth
    comment = models.TextField()
    rating = models.PositiveIntegerField(default=1)  # 1-5 scale
    created_at = models.DateTimeField(auto_now_add=True)

    def clean(self):
        if not (1 <= self.rating <= 5):
            raise ValidationError('Rating must be between 1 and 5')

moviehub/mhub/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="main_account clearfix">
    <section id="center">
        <img src="{% static 'img/addmov.jpg' %}" alt="Avatar" class="banner-image">
        <div class="container-xl">
            <div class="row center_o1">
                <div class="col-md-12">
                    <h2 class="text-Black">About Us</h2>
                </div>
            </div>
        </div>
    </section>
</div>

<section id="feature" class="p_3">
 <div class="container-xl">
  <div class="feature_1 row">
    <div class="col-md-6">
	 <div class="feature_1l clearfix">
	    <h5 class="col_red">SOME FEATURES AND </h5>
		<h1>THE BENEFITS OF USING BACKHOE TODAY</h1>
		<p>We are committed to providing our customers with super exceptional service while offering our employees the best training and a working environment in which they can excel best of all place for more than a half century.</p>
		<p>This company focus has been in place for more than a half century. We are committed to providing our customers with exceptional service while offering our employees the best training best of all and a working environment.</p>
		<div class="feature_1li1 row">
		 <div class="col-md-6">
		  <div class="feature_1li1l clearfix">
		   <h4>Building Companies</h4>
		   <p>Banks &amp; Financial Institutions face a challenging & dynamic environment with…</p>
		  </div>
		 </div>
		 <div class="col-md-6">
		  <div class="feature_1li1l clearfix">
		   <h4>Other Companies</h4>
		   <p>Banks &amp; Financial Institutions face a challenging & dynamic environment with…</p>
		  </div>
		 </div>
		</div>
		<p class="mb-0">We are committed to providing our customers with super exceptional service while offering our employees the best training and a working environment in which they can excel best of all place for more than a half century.</p>
	 </div>
	</div>
	<div class="col-md-6">
	  <div class="feature_1r clearfix">
	    <div class="grid clearfix">
		  <figure class="effect-jazz mb-0">
			<div class="square-container">
				<img src="{% static 'img/mov2.jpg' %}" class="square-img" alt="img25">
			</div>

		  </figure>
	  </div>
	 </div>
	</div>
   </div>
 </div>
</section>



<!--fotter-->
<section id="footer" class="p_3 bg_dark">
	<div class="row footer_2 mt-4 pt-4">
		<div class="col-md-4">
			<div class="footer_2i">
				<h5 class="text-white">Questions? Call 0850-380-6444</h5>
				<p class="text-muted mt-3">Format for custom post types that are not book or you can use else if to specify a second post type the same way as above.</p>
				<select name="categories" class="form-select mt-4 bg-transparent w-50 rounded-0 fw-bold" required="">
					<option value="">English</option>
					<option>French</option>
					<option>Hindi</option>
					<option>American</option>
					<option>German</option>
				</select>
			</div>
		</div>
		<div class="col-md-2">
			<div class="footer_2i">
				<h5 class="text-uppercase col_red mb-3">Play Show</h5>
				<ul class="mb-0 row">
					<li class="col-md-12 col-6 p-0"><a class="text-muted" href="#">Play Show</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Devices</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Tips</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Contact</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Legal Notices</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Our Terms</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-2">
			<div class="footer_2i">
				<h5 class="text-uppercase col_red mb-3">SUPPORT</h5>
				<ul class="mb-0 row">
					<li class="col-md-12 col-6 p-0"><a class="text-muted" href="#">Help Center</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">FAQ</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Account</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Privacy Policy</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Media Center</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Support</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div class="footer_2i">
				<h5 class="text-uppercase col_red mb-3">Newsletter</h5>
				<p class="text-muted mt-3">Format for custom post types that are not book or you can use else if to specify a second post type the same way as above.</p>
				<input class="form-control mt-3 bg-transparent rounded-0" placeholder="Enter Your Email" type="text">
				<h6 class="mb-0 text-uppercase mt-4"><a class="button" href="#"><i class="fa fa-location-arrow me-1"></i> SUBMIT NOW</a></h6>
			</div>
		</div>
	</div>
</section>

	<section id="footer_b">
		<div class="container-xl">
			<div class="row footer_b1 text-center">
				<div class="col-md-12">
					<p class="mb-0 text-muted">© 2024 MOVIE HUB. All Rights Reserved | Design by <a class="col_red" href=" http://www.templateonweb.com">TemplateOnWeb</a></p>
				</div>
			</div>
		</div>
	</section>

<!--footer end-->
	<script>
	window.onscroll = function() {myFunction()};

	var navbar_sticky = document.getElementById("navbar_sticky");
	var sticky = navbar_sticky.offsetTop;
	var navbar_height = document.querySelector('.navbar').offsetHeight;

	function myFunction() {
	  if (window.pageYOffset >= sticky + navbar_height) {
		navbar_sticky.classList.add("sticky")
		document.body.style.paddingTop = navbar_height + 'px';
	  } else {
		navbar_sticky.classList.remove("sticky");
		document.body.style.paddingTop = '0'
	  }
	}
	</script>
{% endblock %}

moviehub/mhub/templates/account.html
{% extends 'base.html' %}
{% load static %} <!-- Add this line -->
{% block body %}
 <div class="main_account clearfix">
    <section id="center">
        <img src="{% static 'img/addmov.jpg' %}" alt="Avatar" class="banner-image">
     <div class="container-xl">
  <div class="row center_o1">
   <div class="col-md-12">
      <h2 class="text-white">Account</h2>
   </div>
  </div>
 </div>
  </section>
 </div>


<section id="account" class="p_3">
    <div class="container-xl">
        <div class="row account_1">
            <!-- Left Side - Registration Form -->
            <div class="col-md-6">
                <div class="account_1l">
                    <h2>Start Your Membership</h2>
                    <div class="container">
                        <h2>Register</h2>
                        <form action="{% url 'account' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <input type="text" class="form-control" name="username" placeholder="User Name" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="text" class="form-control" name="first_name" placeholder="First Name" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="text" class="form-control" name="last_name" placeholder="Last Name" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="email" class="form-control" name="email" placeholder="Enter Email" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="password" class="form-control" name="password" placeholder="Password" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="password" class="form-control" name="conform_password" placeholder="Reenter your Password" required>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Done</button>
                            </div>
                        </form>
                        {% for msg in messages %}
                            <div class="alert alert-info mt-3">{{ msg }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <!-- Right Side - Image Section -->
            <div class="col-md-6">
                <div class="account_1r">
                    <div class="grid clearfix">
                        <figure class="effect-jazz mb-0">
                            <a href="#">
                                <img src="{% static 'img/mov3.jpg' %}" class="w-100" alt="Membership Image">
                            </a>
                        </figure>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!--fotter-->
<section id="footer" class="p_3 bg_dark">
	<div class="row footer_2 mt-4 pt-4">
		<div class="col-md-4">
			<div class="footer_2i">
				<h5 class="text-white">Questions? Call 0850-380-6444</h5>
				<p class="text-muted mt-3">Format for custom post types that are not book or you can use else if to specify a second post type the same way as above.</p>
				<select name="categories" class="form-select mt-4 bg-transparent w-50 rounded-0 fw-bold" required="">
					<option value="">English</option>
					<option>French</option>
					<option>Hindi</option>
					<option>American</option>
					<option>German</option>
				</select>
			</div>
		</div>
		<div class="col-md-2">
			<div class="footer_2i">
				<h5 class="text-uppercase col_red mb-3">Play Show</h5>
				<ul class="mb-0 row">
					<li class="col-md-12 col-6 p-0"><a class="text-muted" href="#">Play Show</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Devices</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Tips</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Contact</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Legal Notices</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Our Terms</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-2">
			<div class="footer_2i">
				<h5 class="text-uppercase col_red mb-3">SUPPORT</h5>
				<ul class="mb-0 row">
					<li class="col-md-12 col-6 p-0"><a class="text-muted" href="#">Help Center</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">FAQ</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Account</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Privacy Policy</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Media Center</a></li>
					<li class="mt-2 col-md-12 col-6 p-0"><a class="text-muted" href="#">Support</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div class="footer_2i">
				<h5 class="text-uppercase col_red mb-3">Newsletter</h5>
				<p class="text-muted mt-3">Format for custom post types that are not book or you can use else if to specify a second post type the same way as above.</p>
				<input class="form-control mt-3 bg-transparent rounded-0" placeholder="Enter Your Email" type="text">
				<h6 class="mb-0 text-uppercase mt-4"><a class="button" href="#"><i class="fa fa-location-arrow me-1"></i> SUBMIT NOW</a></h6>
			</div>
		</div>
	</div>
</section>

	<section id="footer_b">
		<div class="container-xl">
			<div class="row footer_b1 text-center">
				<div class="col-md-12">
					<p class="mb-0 text-muted">© 2024 MOVIE HUB. All Rights Reserved | Design by <a class="col_red" href=" http://www.templateonweb.com">TemplateOnWeb</a></p>
				</div>
			</div>
		</div>
	</section>

<!--footer end-->
	<script>
	window.onscroll = function() {myFunction()};

	var navbar_sticky = document.getElementById("navbar_sticky");
	var sticky = navbar_sticky.offsetTop;
	var navbar_height = document.querySelector('.navbar').offsetHeight;

	function myFunction() {
	  if (window.pageYOffset >= sticky + navbar_height) {
		navbar_sticky.classList.add("sticky")
		document.body.style.paddingTop = navbar_height + 'px';
	  } else {
		navbar_sticky.classList.remove("sticky");
		document.body.style.paddingTop = '0'
	  }
	}
	</script>
{% endblock %}

moviehub/mhub/templates/add_movie.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<style>
    /* Add your custom styles here */
    body {
        background-color: #E6E6FA; /* Light gray background for the entire page */
    }
    .form-background {
        background-color: #E6E6FA; /* White background for the form */
    }

    .text-Black {
        color: black; /* Set text color to black */
        font-size: 2rem; /* Adjust font size */
        text-align: center; /* Center align the text */
        margin-top: 20px; /* Add some space above */

</style>

<div class="main_account clearfix">
    <section id="center">
        <img src="{% static 'img/addmov.jpg' %}" alt="Avatar" class="banner-image">
        <div class="container-xl">
            <div class="row center_o1">
                <div class="col-md-12">
                    <h2 class="text-Black">Add Movie</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <form method="post" enctype="multipart/form-data" class="form-background p-4 rounded shadow-sm">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Add Movie</button>
    </form>
</div>



<script>
    window.onscroll = function() { myFunction() };

    var navbar_sticky = document.getElementById("navbar_sticky");
    var sticky = navbar_sticky.offsetTop;
    var navbar_height = document.querySelector('.navbar').offsetHeight;

    function myFunction() {
        if (window.pageYOffset >= sticky + navbar_height) {
            navbar_sticky.classList.add("sticky");
            document.body.style.paddingTop = navbar_height + 'px';
        } else {
            navbar_sticky.classList.remove("sticky");
            document.body.style.paddingTop = '0';
        }
    }
</script>
{% endblock %}

moviehub/mhub/templates/add_review.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
   <div class="main_account clearfix">
        <section id="center">
            <img src="{% static 'img/addmov.jpg' %}" alt="Avatar" class="banner-image">
            <div class="container-xl">
                <div class="row center_o1">
                </div>
            </div>
        </section>
    </div>
<div class="container">
    <img src="{{ movie.image.url }}"height="200" width="300" alt="{{ movie.title }}" class="img-fluid mb-4">


    <form method="post" action="{% url 'add_review' movie.id %}">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Ensure form fields are displayed correctly -->

        <button type="submit" class="btn btn-primary">Submit Review</button>
    </form>

    <a href="{% url 'index' %}" class="btn btn-secondary mt-3">Back </a>
</div>
{% endblock %}

moviehub/mhub/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>MOVIE HUB</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" >
	<link href="{% static 'css/global.css' %}" rel="stylesheet">
	<link href="{% static 'css/index.css' %}" rel="stylesheet">
	<link href="{% static 'https://fonts.googleapis.com/css2?family=Overpass&display=swap' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/flipcard.css' %}">




</head>
<body>
<!--NAVBAR-->
<div class="main clearfix position-relative">
 <div class="main_1 clearfix position-absolute top-0 w-100">
   <section id="header">
<nav class="navbar navbar-expand-md navbar-light" id="navbar_sticky">
  <div class="container-xl">
    <a class="navbar-brand fs-2 p-0 fw-bold text-white m-0 me-5" href="{% url 'index' %}">MOVIE HUB </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	   <ul class="navbar-nav mb-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>

		<li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About </a>
        </li>
           <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   Category
               </a>
               <ul class="dropdown-menu drop_1" aria-labelledby="navbarDropdown">
                   {% for category in categories %}
                   <li><a class="dropdown-item" href="{% url 'category' category.id %}">{{ category.name }}</a></li>
                   {% endfor %}
               </ul>
           </li>

		<li class="nav-item">
          <a class="nav-link" href="{% url 'add_movie' %}">Add Movie</a>
        </li>

		<li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>

      </ul>
      <ul class="navbar-nav mb-0 ms-auto">
	   <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle dropdown_search" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
        <i class="fa fa-search"></i>
    </a>
    <ul class="dropdown-menu drop_1 drop_o p-3" aria-labelledby="navbarDropdown" data-bs-popper="none">
        <li>
            <form class="input-group p-2" action="{% url 'search' %}" method="GET">  <!-- Pointing to the search URL -->
                <input type="text" class="form-control border-0" name="q" placeholder="Search Here" required>  <!-- Added name attribute for form submission -->
                <span class="input-group-btn">
                    <button class="btn btn-primary bg-transparent border-0 fs-5" type="submit">  <!-- Changed type to submit -->
                        <i class="fa fa-search col_red"></i>
                    </button>
                </span>
            </form>
        </li>
    </ul>
</li>


		  {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account' %}">Account</a>
            </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
       <!-- User welcome message below the navigation bar -->
<div id="welcome-message">
    {% if user.is_authenticated %}
        <p>Hello, {{ user.username }}!</p>
    {% endif %}
</div>
</section>
 </div>
</div>
{% block body %}
{% endblock %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

moviehub/mhub/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="main_account clearfix">
        <section id="center">
            <img src="{% static 'img/addmov.jpg' %}" alt="Avatar" class="banner-image">
            <div class="container-xl">
                <div class="row center_o1">
                </div>
            </div>
        </section>
    </div>

<section id="stream" class="p_3">
    <div class="container-xl">
        <div class="row stream_1">
            <div class="col-md-12">
                <h1 class="mb-0">Movies in {{ category.name }}</h1>
            </div>
        </div>

        <!-- First row for movies -->
        <div class="row stream_2 mt-6 clearfix">
            {% for movie in movies %}
                <div class="col-md-3 pe-0 mb-4">
                    <div class="flip-card">
                        <div class="flip-card-inner">
                            <div class="flip-card-front">
                                <img src="{{ movie.image.url }}" class="w-100" alt="{{ movie.name }}">
                            </div>
                            <div class="flip-card-back p-3">
                                <h6 class="font_16 col_red">{{ movie.category.name }}</h6>
                                <h4 class="text-Black">{{ movie.name }}</h4>
                                <p>{{ movie.description }}</p>
                                <p><strong>Release Year:</strong> {{ movie.release_year }}</p>
                                <p><strong>Actors:</strong> {{ movie.actors }}</p>
                                <h5 class="text-Black">
                                    <a class="text-Black align-middle lh-1" href="{{ movie.youtube_trailer_link }}" target="_blank">
                                        <i class="fa fa-play-circle"></i> Watch Trailer
                                    </a>
                                </h5>

                                <!-- Review Section -->
                                <div class="review-section">
                                    <form method="post" action="{% url 'add_review' movie.id %}">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button type="submit" class="btn btn-primary">Submit Review</button>
                                    </form>
                                    <a href="{% url 'movie_detail' movie.id %}" class="btn btn-primary mt-2">View Review</a>
                                    {% for review in movie.reviews.all %}
                                    <div class="review">
                                        <div class="star-rating">
                                            <p><strong>{{ review.user.username }}</strong>
                                            {% for i in "12345"|slice:":review.rating"|make_list %}
                                                <i class="fas fa-star text-warning"></i>
                                            {% endfor %}
                                            {% for i in "12345"|slice:":5-review.rating"|make_list %}
                                                <i class="far fa-star"></i>
                                            {% endfor %}
                                            </p>
                                        </div>
                                        <p>{{ review.comment }}</p>
                                        <small>{{ review.created_at }}</small>
                                    </div>
                                    {% empty %}
                                        <p>No reviews yet. Be the first to review!</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Start a new row after every 4 movies -->
                {% if forloop.counter|divisibleby:4 %}
                    </div><div class="row stream_2 mt-6 clearfix">
                {% endif %}

            {% empty %}
                <p>No movies found in this category.</p>
            {% endfor %}
        </div> <!-- End of row -->
    </div>
</section>
{% endblock %}

moviehub/mhub/templates/delete.html
<h2>Are you sure you want to delete "{{ movie.title }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'profile' %}">Cancel</a>
</form>

moviehub/mhub/templates/profile_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ user.username }}'s Profile</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <style>
        /* Main container */
        .profile-container {
            max-width: 600px;
            margin: 50px auto;
            text-align: center;
            font-family: Arial, sans-serif;
        }

        /* Profile Picture */
        .profile-picture {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            object-fit: cover;
            border: 3px solid #ddd;
            margin-bottom: 10px;
        }

        /* Username and bio section */
        .username {
            font-size: 24px;
            font-weight: bold;
            color: #333;
            margin-top: 10px;
        }

        .bio, .location {
            color: #777;
            font-size: 14px;
        }

        /* Button styles */
        .btn {
            display: inline-block;
            padding: 10px 20px;
            margin-top: 15px;
            font-size: 14px;
            font-weight: bold;
            text-decoration: none;
            color: white;
            background-color: #3897f0; /* Instagram-like blue */
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .btn:hover {
            background-color: #2a7fc0;
        }

        /* Profile details */
        .profile-details {
            margin-top: 20px;
            color: #444;
        }

        /* Section spacing */
        .section {
            margin-top: 15px;
        }

        /* Movies section */
        .movies-section {
            margin-top: 30px;
            text-align: left;
        }

        .movie-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 10px;
            background-color: #f9f9f9;
        }

        .movie-title {
            font-weight: bold;
        }

        .movie-buttons {
            display: flex;
            gap: 10px;
        }

        .delete-btn {
            background-color: #ff4d4d; /* Red color for delete */
        }

        .delete-btn:hover {
            background-color: #ff1a1a; /* Darker red on hover */
        }
    </style>
</head>
<body>

<div class="profile-container">
    {% if user.profile.profile_picture %}
        <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" class="profile-picture">
    {% else %}
        <img src="https://via.placeholder.com/120" alt="Default Profile Picture" class="profile-picture">
    {% endif %}

    <div class="username">{{ user.username }}</div>

    <div class="profile-details">
        <div class="bio section">{{ user.profile.bio }}</div>
        <div class="location section"><i class="fas fa-map-marker-alt"></i> {{ user.profile.location }}</div>
        <div class="section"><strong>Email:</strong> {{ user.email }}</div>
    </div>

    <a href="{% url 'edit_profile' %}" class="btn btn-primary">Edit Profile</a>

    <!-- Back to Home Button -->
    <a href="/" class="btn">Back to Home</a> <!-- Adjust the URL to your home page if necessary -->

   <div class="movies-section">
       <h3>Your Movies</h3>
       {% for movie in user.movie_set.all %}
       <div class="movie-item">
           <div class="movie-title">{{ movie.name }}</div>
           <div class="movie-buttons">
               <a href="{% url 'edit_movie' movie.id %}" class="btn">Edit</a>
               <form action="{% url 'delete_movie' movie.id %}" method="post" style="display:inline;">
                   {% csrf_token %}
                   <button type="submit" class="btn delete-btn">Delete</button>
               </form>
           </div>
       </div>
       {% empty %}
       <div class="section">You have not added any movies yet.</div>
       {% endfor %}
   </div>
</div>

</body>
</html>